### ISSUE TITLE
老哥你们服务器部署的跑不动啊

### ISSUE THREAD

**Issue by kekehatui** [jcchan23/SAIL#1]
graphsol和spider3用例子runing后就failed了

**Comment by kekehatui** [comment]
老哥你的.pssm格式的文件是怎么用.asn处理出来的呢

**Comment by jcchan23** [comment]
嗯嗯，开学之后我就跟服务器那边的工程师沟通过，但是目前他们好像还没有修复好...有空的时候我再去问问他们。

pssm文件需要使用psi-blast软件，建立NR90数据库等索引跑出来的。
https://blast.ncbi.nlm.nih.gov/Blast.cgi?PAGE_TYPE=BlastSearch&PROGRAM=blastp&BLAST_PROGRAMS=psiBlast

**Comment by kekehatui** [comment]
在这个网站3次迭代后有个down all 不管选下载asn file还是pssm file得到的都是.asn格式的文件，是这样吗，需要自己处理吗

![1646124304(1)](https://user-images.githubusercontent.com/49575506/156135547-1f36f6c5-2245-412a-87eb-cf72b5fb783d.jpg)

**Comment by jcchan23** [comment]
应该是的，不过我没处理过这个asn格式的文件，之前是大批量生成pssm矩阵所以都是下载了blast软件然后部署到服务器上去生成的，现在已经到2.11.0版本了。
https://blast.ncbi.nlm.nih.gov/Blast.cgi?CMD=Web&PAGE_TYPE=BlastNews
