### ISSUE TITLE
老哥是用dca.m生成.di文件的吗

### ISSUE THREAD

**Issue by kekehatui** [jcchan23/SAIL#2]
得到的是哪种di文件呢
![1646791533(1)](https://user-images.githubusercontent.com/49575506/157358358-da8e460d-e325-4fff-a4ea-af7400af00aa.jpg)
![1646791551(1)](https://user-images.githubusercontent.com/49575506/157358360-8ca4e791-0901-4ca8-90b6-4a5fd83e052b.jpg)

**Comment by jcchan23** [comment]
第二种

**Comment by kekehatui** [comment]
老哥用的是这个版本的dca.m吗，没看着有版本号👀
![1646792472(1)](https://user-images.githubusercontent.com/49575506/157360025-47e05f90-e3d3-4aeb-bd8b-4bdbeb144084.jpg)

**Comment by jcchan23** [comment]
没看着这个，当时我用的是SPOT-Contact软件去生成Predicted Contact Map，但是它的前置输入有太多个了，所以我是把它全部剥离出来然后并行生成所需特征，最后再一并输入到SPOT-Contact当中，所以我直接用的是它给的二进制可执行文件。

**Comment by kekehatui** [comment]
用的SPOT-Contact包里自带了CCMpred和DCA吗，老哥并行生成得怎么操作呢
![1646793316(1)](https://user-images.githubusercontent.com/49575506/157361507-88f21058-9ab9-456d-aed6-daf7be9cf3af.jpg)

**Comment by jcchan23** [comment]
CCMpred和DCA的输入是由前面HH-Suite3软件附带生成的a3m文件，然后DCA是用里面的main可执行脚本，CCMpred使用bin下的CCMpred可执行脚本，我记得Spot-Contact里面有一个run.sh有命令说明怎么调用DCA和CCMpred。再然后把这些命令单独抽离出来，利用bash写多进程运行这些命令就好，直接上网查就行，比如可以用bash创建管道，再申请多个进程。

**Comment by jcchan23** [comment]
就如果你不是执着于一定要用SPOT-Contact生成Predicted Contact Map的话，我推荐你先生成前面3个特征，即PSSM，HMM和SPIDER3，然后邻接矩阵直接输入一个对角矩阵+2阶副对角矩阵（即paper里提到的α=0的邻接矩阵），先测试下这样子的输入在你的数据集上的效果，再考虑Predicted Contact Map，后者只是能够做到一点性能提升，但却需要耗费大量的计算时间去生成di,mat和spotcon特征。

**Comment by kekehatui** [comment]
好的好的感谢感谢，我先做起来
